'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CalculatorSuite

    '''<summary>
    '''ddlCalculators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCalculators As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCalcTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalcTitle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCalcDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalcDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrint As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''mvCalculators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mvCalculators As Global.System.Web.UI.WebControls.MultiView

    '''<summary>
    '''viewAlgebraAdvanced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewAlgebraAdvanced As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlAlgebra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAlgebra As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtAlgExpression control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAlgExpression As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAlgEval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlgEval As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAlgClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAlgClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAlgResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlgResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divAlgHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAlgHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewBMI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewBMI As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlBMI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBMI As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtBMIWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBMIWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBMIWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBMIWeightUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBMIHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBMIHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBMIHeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBMIHeightUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBMIAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBMIAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBMIGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBMIGender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnBMICalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBMICalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBMIResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBMIResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divBMIHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBMIHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewBMR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewBMR As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlBMR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBMR As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtBMRWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBMRWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBMRWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBMRWeightUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBMRHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBMRHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBMRHeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBMRHeightUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBMRAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBMRAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBMRGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBMRGender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlBMRActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBMRActivity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnBMRCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBMRCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBMRResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBMRResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divBMRHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBMRHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewBreakEven control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewBreakEven As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlBreakEven control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlBreakEven As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtBreakEvenFixed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBreakEvenFixed As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBreakEvenPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBreakEvenPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBreakEvenVariable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBreakEvenVariable As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBreakEvenTargetProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBreakEvenTargetProfit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBreakEvenCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBreakEvenCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBreakEvenResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBreakEvenResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divBreakEvenHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBreakEvenHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewCalorieIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCalorieIntake As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlCalorie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCalorie As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCalorieWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalorieWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCalorieWeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCalorieWeightUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCalorieHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalorieHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCalorieHeightUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCalorieHeightUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtCalorieAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCalorieAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCalorieGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCalorieGender As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlCalorieActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCalorieActivity As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlFitnessGoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFitnessGoal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCalorieCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCalorieCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCalorieResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCalorieResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divProteinBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divProteinBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCarbBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCarbBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divFatBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFatBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCalorieHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCalorieHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewCarLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCarLoan As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlCarLoan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCarLoan As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCarLoanAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarLoanAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCarLoanRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarLoanRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCarLoanMonths control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarLoanMonths As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCarLoanExtra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCarLoanExtra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCarLoanCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCarLoanCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCarLoanResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCarLoanResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divCarLoanAmortization control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCarLoanAmortization As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divCarLoanHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCarLoanHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewChemistryMolarity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewChemistryMolarity As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlMolarity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlMolarity As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlAmountUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAmountUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtMolarMass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMolarMass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVolume As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlVolumeUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVolumeUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnMolarityCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMolarityCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMolarityResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMolarityResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divMolarityHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMolarityHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewCompoundInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCompoundInterest As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlCompoundInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCompoundInterest As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCIPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCIPrincipal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCIRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCIRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCIYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCIYears As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCICompounds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCICompounds As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCIExtra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCIExtra As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCIExtraFreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCIExtraFreq As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCICalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCICalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCIResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCIResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divCIHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCIHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewCryptoROI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCryptoROI As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlCrypto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCrypto As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCryptoInvestment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCryptoInvestment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCryptoFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCryptoFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCryptoYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCryptoYears As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCryptoContribution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCryptoContribution As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCryptoFreq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCryptoFreq As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnCryptoCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCryptoCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCryptoResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCryptoResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divCryptoHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCryptoHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewCurrencyConverter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewCurrencyConverter As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''pnlCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlCurrency As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtCurrencyAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrencyAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCurrencyRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrencyRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCurrencyFee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrencyFee As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCurrencyExtraRates control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrencyExtraRates As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCurrencyCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCurrencyCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCurrencyResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrencyResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divCurrencyHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCurrencyHistory As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''viewGoalPlanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewGoalPlanner As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtGoalDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoalDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoalDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoalDays As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGoalCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoalCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblGoalResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoalResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewHeartRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewHeartRate As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtHRAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHRAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnHRCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHRCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblHRResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHRResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewInventoryTurnover control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewInventoryTurnover As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtCOGS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCOGS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAvgInventory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAvgInventory As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnInventoryCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInventoryCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblInventoryResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInventoryResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewIRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewIRR As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtIRRInvestment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIRRInvestment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIRRFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIRRFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnIRRCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIRRCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblIRRResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIRRResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewLoanAmort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewLoanAmort As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtLoanAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoanAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLoanInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoanInterest As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLoanTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoanTerm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnLoanAmortCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLoanAmortCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblLoanAmortResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLoanAmortResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewMacro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewMacro As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtMacroCalories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMacroCalories As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMacroProtein control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMacroProtein As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMacroCarbs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMacroCarbs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMacroFat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMacroFat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnMacroCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMacroCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMacroResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMacroResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewMarkupMargin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewMarkupMargin As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnMarkupCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMarkupCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMarkupResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMarkupResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewMortgageCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewMortgageCalc As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtMortgageAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMortgageAmt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMortgageInterest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMortgageInterest As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMortgageTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMortgageTerm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnMortgageCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMortgageCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMortgageResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMortgageResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewNPV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewNPV As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtNPVInvestment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNPVInvestment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNPVFuture control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNPVFuture As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNPVRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNPVRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnNPVCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNPVCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblNPVResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNPVResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewPetDosage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPetDosage As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtPetWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPetWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPetDose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPetDose As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPetCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPetCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPetResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPetResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewPhysics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPhysics As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtMass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAcceleration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcceleration As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPhysicsCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPhysicsCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPhysicsResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhysicsResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewPriceProfit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPriceProfit As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtPriceCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPriceSale control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPriceSale As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPriceProfitCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPriceProfitCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPriceProfitResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPriceProfitResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewPregnancyCalorie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPregnancyCalorie As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtPregWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPregWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPregHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPregHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPregTrimester control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPregTrimester As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPregCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPregCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPregResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPregResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewProductivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewProductivity As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtProdTasks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdTasks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtProdCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProdCompleted As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnProdCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProdCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblProdResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProdResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewQuadratic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewQuadratic As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtQuadA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuadA As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQuadB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuadB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQuadC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuadC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnQuadCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnQuadCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblQuadResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuadResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewRetirement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewRetirement As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtRetSavings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRetSavings As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRetContribution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRetContribution As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRetYears control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRetYears As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnRetCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRetCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblRetResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRetResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewROI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewROI As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtROIInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtROIInit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtROIFinalVal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtROIFinalVal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnROICalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnROICalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblROIResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblROIResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewSavingsGoal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewSavingsGoal As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtGoalAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoalAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGoalMonthly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGoalMonthly As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnGoalAmountCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGoalAmountCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblGoalAmountResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGoalAmountResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewSleepNeeds control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewSleepNeeds As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtSleepAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSleepAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSleepCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSleepCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSleepResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSleepResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewStockInvestment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewStockInvestment As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtStockInit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStockInit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStockFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStockFinal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnStockCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStockCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStockResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStockResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewStudyPlanner control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewStudyPlanner As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtStudyTotalHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStudyTotalHours As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtStudySubjects control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStudySubjects As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnStudyCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStudyCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStudyResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStudyResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewTDEE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewTDEE As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtTDEEWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTDEEWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTDEEHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTDEEHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTDEEAge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTDEEAge As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTDEEGender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTDEEGender As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTDEEActivity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTDEEActivity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnTDEECalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTDEECalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTDEResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTDEResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewTravelFuel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewTravelFuel As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtTravelDistance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTravelDistance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTravelEfficiency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTravelEfficiency As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTravelFuelPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTravelFuelPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnTravelCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnTravelCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblTravelResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTravelResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewUnitConversion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewUnitConversion As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtUnitValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitValue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnitFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitFrom As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtUnitTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitTo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUnitConvert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUnitConvert As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblUnitResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnitResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewVAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewVAT As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtVATPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVATPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVATRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVATRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnVATCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVATCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblVATResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVATResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewPomodoro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewPomodoro As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtPomWork control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPomWork As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPomBreak control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPomBreak As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnPomodoroStart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPomodoroStart As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblPomResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPomResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewWaterIntake control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewWaterIntake As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtWaterWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWaterWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnWaterCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWaterCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblWaterResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWaterResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewChemMolarity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewChemMolarity As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtChemMoles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChemMoles As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtChemVolume control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChemVolume As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnChemCalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnChemCalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblChemResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChemResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''viewBSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewBSA As Global.System.Web.UI.WebControls.View

    '''<summary>
    '''txtBSAWeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBSAWeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBSAHeight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBSAHeight As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnBSACalc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBSACalc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblBSAResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBSAResult As Global.System.Web.UI.WebControls.Label
End Class
